title: "Patcharapon Sangsatra Portfolio"
description: "Built by using Markdown and GitHub Actions"
baseurl: "" 
url: "https://patcharapon-san.github.io"
theme: minima

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
